specVersion: 0.2.0
name: solarbeam-eclipse-subquery
version: 1.0.0
description: Eclipse subquery
repository: https://github.com/solarbeamio/solarbeam-eclipse-subquery
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x401a1f9dca3da46f5c4091016c8a2f26dcea05865116b286f60f668207d1474b'
  endpoint: wss://moonriver.api.onfinality.io/public-ws
  dictionary: 'https://api.subquery.network/sq/subquery/moonriver-dictionary'
  chaintypes:
    file: "./types.yaml"
dataSources:
  - kind: substrate/Moonbeam
    startBlock: 807763
    processor:
      file: './node_modules/@subql/contract-processors/dist/moonbeam.js'
      options:
        abi: commonEclipse
        address: '0x022Bcb66662Bb3854b6f16bAbD4c13BFa3dB0b08'
    assets:
      commonEclipse:
        file: './abis/CommonEclipse.json'
    mapping:
      file: './dist/index.js'
      handlers:
        - handler: handleDepositEvent
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - Deposit(address indexed user, uint256 amount, uint256 indexed pid)
        - handler: handleWithdrawEvent
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - Withdraw(address indexed user, uint256 amount, uint256 indexed pid)
